name: Deploy
on:
  push:
    branches:
      - main
      - feature/#2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: PRD
    steps:
      - uses: actions/checkout@v2
      - name: setup aws config
        run: |
          mkdir ${HOME}/.aws
          touch ${HOME}/.aws/config
          echo [default] >> ${HOME}/.aws/config
          echo aws_access_key_id=${{ secrets.AWS_ACCESS_KEY }} >> ${HOME}/.aws/config
          echo aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ${HOME}/.aws/config
          echo region=ap-northeast-1 >> ${HOME}/.aws/config
          echo output=json >> ${HOME}/.aws/config
          echo ${{ secrets.AWS_ACCESS_KEY }}
          cat ${HOME}/.aws/config
      - name: Docker build
        run: make docker-build
      - name: cfn deploy
        run: make deploy-all ENV=${{ secrets.ENV }}
