name: Testing
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup aws config
        run: |
          mkdir ${HOME}/.aws
          touch ${HOME}/.aws/config
          echo [profile prd] >> ${HOME}/.aws/config
          echo aws_access_key_id=${AWS_ACCESS_KEY} >> ${HOME}/.aws/config
          echo aws_secret_access_key=${AWS_SECRET_ACCESS_KEY} >> ${HOME}/.aws/config
          echo region=ap-northeast-1 >> ${HOME}/.aws/config
          echo output=json >> ${HOME}/.aws/config
      - name: Docker build
        run: make docker-build
      - name: cfn linter
        run: make cfn-lint
